{
          gameVersion: pokemon_v2_version {
            id
            name
          }
          pkm: pokemon_v2_pokemon(where: {name: {_eq: ${pokemon.pokemon.name} }}) {
            name
            id
            forms: pokemon_v2_pokemonforms {
              form_name
              name
              is_battle_only
              is_mega
              is_default
            }
            abilities: pokemon_v2_pokemonabilities {
              is_hidden
              ability: pokemon_v2_ability {
                name
              }
            }
            moves: pokemon_v2_pokemonmoves {
              move_learn_method_id
              level
              order
              version_group_id
              move: pokemon_v2_move {
                name
                accuracy
                power
                pp
              }
              learnMethod: pokemon_v2_movelearnmethod {
                name
              }
            }
            stats: pokemon_v2_pokemonstats {
              base_stat
              effort
              stat: pokemon_v2_stat {
                name
              }
            }
            types: pokemon_v2_pokemontypes {
              slot
              type: pokemon_v2_type {
                name
              }
            }
            species: pokemon_v2_pokemonspecy {
              base_happiness
              evolution_chain_id
              evolves_from_species_id
              hatch_counter
              is_baby
              is_mythical
              is_legendary
              order
              eggGroup: pokemon_v2_pokemonegggroups {
                group: pokemon_v2_egggroup {
                  name
                }
              }
              genus: pokemon_v2_pokemonspeciesnames {
                genus
              }
              flavorTexts: pokemon_v2_pokemonspeciesflavortexts {
                flavor_text
                gameVersion: pokemon_v2_version {
                  name
                }
              }
              pokedex: pokemon_v2_pokemondexnumbers {
                dexNo: pokemon_v2_pokedex {
                  name
                  id
                }
              }
              growth: pokemon_v2_growthrate {
                name
              }
              evolutions: pokemon_v2_pokemonevolutions {
                min_level
                min_happiness
                min_affection
                min_beauty
                time_of_day
                turn_upside_down
                trigger: pokemon_v2_evolutiontrigger {
                  name
                }
                gender: pokemon_v2_gender {
                  name
                }
                item: pokemon_v2_item {
                  name
                }
                location: pokemon_v2_location {
                  name
                }
                evoName: pokemon_v2_pokemonspecy {
                  name
                }
              }
            }
          }
        } 